### ISSUE TITLE
Can it be like vim :tabnext(gt)?

### ISSUE THREAD

**Issue by msdone-lwt** [jackiotyu/vscode-switch-file#2]
Would it be possible to switch only the most recently opened files instead of files in the same directory, like vim switches tabs?
![image](https://github.com/jackiotyu/vscode-switch-file/assets/103359349/5b71ff1a-b8ac-4e13-87b8-3bd0e7dd5ecd)

**Comment by jackiotyu** [comment]
~~Yes, I'll implement this feature later.😃~~
![image](https://github.com/jackiotyu/vscode-switch-file/assets/31788042/a189515a-23f8-45a9-ab43-26efe20132da)
You can just use the built-in command in vscode.
